"""Golden-file tests for the deterministic composer — PRODUCT_BOOK section 10.

The deterministic composer must be reproducible: it is the fallback path, the
benchmark baseline, and the thing a user gets when anything else misbehaves.
A diff here is not necessarily a bug, but it is always a decision -- if the
change is intended, regenerate with:

    python -m prayer.api.build.golden
"""
import json

from prayer import paths
from pathlib import Path

import pytest

from prayer.api.analyze import SituationAnalyzer
from prayer.api.composers.deterministic import DeterministicComposer
from prayer.api.composers.verify import spoken_text

# Generated by `make golden`; lives in the build tree, not in git. Skip rather
# than raise at import: a missing fixture would otherwise abort collection for
# the WHOLE suite, turning one absent file into 183 unexplained failures. CI
# guards the opposite risk -- a silently empty build looking green -- by
# asserting every artifact exists before it runs pytest.
GOLDEN = paths.FIXTURES / "golden_compositions.json"
if not GOLDEN.exists():
    pytest.skip(f"missing {GOLDEN}; run `make golden`", allow_module_level=True)
CASES = json.loads(GOLDEN.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def composer(corpus, settings):
    return DeterministicComposer(corpus, settings)


@pytest.fixture(scope="module")
def analyzer(settings):
    return SituationAnalyzer(settings.policy_dir)


@pytest.mark.parametrize("case", CASES, ids=[c["prayer_id"] for c in CASES])
def test_composition_matches_golden(corpus, composer, analyzer, case):
    q = analyzer.analyze(case["situation"])
    record = corpus.record(case["prayer_id"])
    composition = composer.compose(q, record, corpus.passage(case["prayer_id"]))

    assert spoken_text(composition) == case["spoken_text"]
    assert [m.model_dump() for m in composition.movements] == case["movements"]
    assert composition.instructions.model_dump() == case["instructions"]


@pytest.mark.parametrize("case", CASES, ids=[c["prayer_id"] for c in CASES])
def test_composition_is_stable_across_calls(corpus, composer, analyzer, case):
    """Same request twice must give the same prayer, not a variant."""
    q = analyzer.analyze(case["situation"])
    record = corpus.record(case["prayer_id"])
    passage = corpus.passage(case["prayer_id"])
    first = spoken_text(composer.compose(q, record, passage))
    second = spoken_text(composer.compose(q, record, passage))
    assert first == second


def test_golden_anchors_are_still_verbatim(corpus):
    """Guards against a golden file that was regenerated over a real bug."""
    for case in CASES:
        passage = corpus.passage(case["prayer_id"])
        anchor = next(m for m in case["movements"] if m["kind"] == "anchor")
        assert anchor["text"] in passage.full_text
