#!/usr/bin/env python3
"""In-memory corpus, loaded once at startup.

224 records and their passages are a few megabytes; there is no reason for a
database, and holding it in memory keeps the request path free of I/O (C3).

The Corpus owns three things a request needs and nothing else does:
the annotation records, the resolved WEB text, and the vocabulary definitions.
Retrievers and composers receive slices of it rather than reaching for globals,
so a test can build a five-record Corpus and drive the whole pipeline.
"""
import csv
import json
from pathlib import Path
from typing import Optional

import yaml

from prayer.api.models import Passage, PrayerRecord

PSALM_BOOK = "Ps"


class Corpus:
    def __init__(self, records: list[PrayerRecord], passages: dict[str, Passage],
                 content_defs: dict[str, str], context_defs: dict[str, str],
                 translation: str = "WEB"):
        self.records = records
        self.by_id = {r.id: r for r in records}
        self.passages = passages
        self.content_defs = content_defs
        self.context_defs = context_defs
        self.translation = translation

    # --- accessors ---------------------------------------------------------

    def record(self, prayer_id: str) -> Optional[PrayerRecord]:
        return self.by_id.get(prayer_id)

    def passage(self, prayer_id: str) -> Optional[Passage]:
        return self.passages.get(prayer_id)

    def has_text(self, prayer_id: str) -> bool:
        p = self.passages.get(prayer_id)
        return bool(p and p.text_available and p.full_text.strip())

    def is_psalm(self, prayer_id: str) -> bool:
        r = self.by_id.get(prayer_id)
        return bool(r and r.refs and r.refs[0].book == PSALM_BOOK)

    @property
    def composable(self) -> list[PrayerRecord]:
        """Records eligible for retrieval: policy-allowed and text-resolved."""
        return [r for r in self.records
                if r.compose_policy != "exclude" and self.has_text(r.id)]

    def stats(self) -> dict[str, int]:
        return {
            "prayers": len(self.records),
            "passages": sum(1 for p in self.passages.values() if p.text_available),
            "retrievable": len(self.composable),
            "excluded_by_policy": sum(1 for r in self.records
                                      if r.compose_policy == "exclude"),
            "explain_only": sum(1 for r in self.records
                                if r.compose_policy == "explain_only"),
        }


# --- loading ---------------------------------------------------------------

def _load_records(dataset_dir: Path) -> list[PrayerRecord]:
    path = dataset_dir / "prayers.jsonl"
    records = []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(PrayerRecord.model_validate_json(line))
    return records


def _load_defs(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    with path.open(encoding="utf-8", newline="") as fh:
        return {row["id"]: row["definition"] for row in csv.DictReader(fh)}


def _load_passages(text_dir: Path, translation: str) -> dict[str, Passage]:
    path = text_dir / f"{translation.lower()}.jsonl"
    if not path.exists():
        return {}
    out = {}
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                p = Passage.model_validate_json(line)
                out[p.prayer_id] = p
    return out


def _apply_policy(records: list[PrayerRecord], policy_dir: Path) -> None:
    """Overlay api/policy/compose_policy.yaml onto the records.

    Kept as a separate curated file rather than a dataset column: the dataset
    is regenerated by prayer.extract.parks and would overwrite it, and this
    file is the one a human signs off on (PRODUCT_BOOK section 7.2).
    """
    path = policy_dir / "compose_policy.yaml"
    if not path.exists():
        return
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    entries = doc.get("prayers", {}) or {}
    by_id = {r.id: r for r in records}
    for prayer_id, entry in entries.items():
        rec = by_id.get(prayer_id)
        if rec is None:
            continue
        if isinstance(entry, str):
            rec.compose_policy = entry  # type: ignore[assignment]
        else:
            rec.compose_policy = entry.get("policy", "compose")
            rec.policy_reason = entry.get("reason")


def load_corpus(dataset_dir: Path, text_dir: Path, policy_dir: Path,
                translation: str = "WEB") -> Corpus:
    records = _load_records(dataset_dir)
    _apply_policy(records, policy_dir)
    return Corpus(
        records=records,
        passages=_load_passages(text_dir, translation),
        content_defs=_load_defs(dataset_dir / "vocab/contents.csv"),
        context_defs=_load_defs(dataset_dir / "vocab/contexts.csv"),
        translation=translation,
    )
